version: '3.8' # Specify the Docker Compose file format version

services:
  react-app:
    build:
      context: ./React-app/ # Path to your React app Dockerfile
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Map port 3000 on the host to port 3000 in the container
    depends_on:
      - elasticsearch # Ensure Elasticsearch starts before the React app
    environment:
      - REACT_APP_ELASTICSEARCH_URL=http://elasticsearch:9200 # Environment variable for React app to connect to Elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2 # Use an appropriate Elasticsearch version
    container_name: elasticsearch
    environment:
      - discovery.type=single-node # Run Elasticsearch in single-node mode
      - xpack.security.enabled=false # Disable security for simplicity (not recommended for production)
    ports:
      - "9200:9200" # Elasticsearch HTTP port
      - "9300:9300" # Elasticsearch transport port
    volumes:
      - es_data:/usr/share/elasticsearch/data # Persistent volume for Elasticsearch data

volumes:
  es_data:
